FROM mariadb/maxscale:24.02

USER root

# instalar iproute2 (binario ip)
RUN (apt-get update && apt-get install -y iproute2) || \
    (yum install -y iproute) || \
    (microdnf install -y iproute) || true

USER maxscale